language: python
python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
env:
  global:
  - secure: exbot0LTV/0Wic6ElKCrOZmh2ZrieuGwEqfYKf5rVuwu1sLngYRihh+lBL/hTwc79NSu829pbwiWfsQZrXbk/yvaS7avGR0CLDoipyPxlYa2/rfs/o4OdTZqXv0LcFmmd54j5QBMpWU1S+CYOwNkwas57trrvIpPbzWjMtfYzOU=
matrix:
  allow_failures:
  - python: '3.2'
  - python: '3.3'
install:
- pip install .
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
- sudo curl -L -o /usr/local/bin/orchard https://github.com/orchardup/go-orchard/releases/download/2.0.4/linux
- sudo chmod +x /usr/local/bin/orchard
before_script: orchard hosts create $TRAVIS_JOB_ID
script: script/travis
after_script: orchard hosts rm -f $TRAVIS_JOB_ID
deploy:
  provider: pypi
  user: orchard
  password:
    secure: M8UMupCLSsB1hV00Zn6ra8Vg81SCFBpbcRsa0nUw9kgXn9hOCESWYVHTqQ1ksWZOa8z6WMaqYtoosPKXGJQNf0wF/kEVDsMUeaZWOF/PqDkx1EwQ1diVfwlbN4/k0iX+Se7SrZfiWnJiAqiIPqToQipvLlJohqf8WwfPcVvILVE=
  on:
    tags: true
    repo: orchardup/fig
