sudo: required

language: python

matrix:
  include:
    - os: linux
      services: [docker]
      env:
        - TOX_ENV=py27
        - TEST_SUITE=tests
        - DOCKER_VERSIONS=1.9.1
        - BUILD_BINARY=true

    - os: linux
      services: [docker]
      env: [TOX_ENV=py27, TEST_SUITE=tests, DOCKER_VERSIONS=1.10.0-rc1]

    - os: linux
      services: [docker]
      env: [TOX_ENV=py34, TEST_SUITE=tests/unit]

    - os: osx
      language: generic
      env: [TOX_ENV=py27, TEST_SUITE=tests/unit, BUILD_BINARY=true]

install: ./script/travis/install

script:
  - ./script/travis/ci
  - ./script/travis/build-binary

before_deploy:
  - "./script/travis/render-bintray-config.py < ./script/travis/bintray.json.tmpl > ./bintray.json"

deploy:
  provider: bintray
  user: docker-compose-roleuser
  key: '$BINTRAY_API_KEY'
  file: ./bintray.json
  skip_cleanup: true
