name: dispatch release event to downstream repositories

on:
  workflow_dispatch:

jobs:
  dispatch_release_version:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_DOC_TOKEN }}
          repository: crazy-max/docker.github.io
          event-type: my-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
