name: 'Close stale issues'
on:
  schedule:
    - cron: '0 0 * * *' # once per day

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          debug-only: true
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs. Thank you
            for your contributions.
          days-before-issue-stale: 180
          days-before-issue-close: 180
          stale-issue-label: "stale"
          exempt-issue-labels: "kind/feature"
          